### ISSUE TITLE
Enemies on level 5 aren't exactly on ground level

### ISSUE THREAD

**Issue by Scruffy21** [EdwardDunn/Platform-Game#103]
I don't know if that was the intention, but on level 5, the spider-like enemy appears some pixels below the ground level. It's still possible to kill it, but it looks weird and is very easy to jump over.

The red enemies there aren't on the exact ground position either but a bit below it.

**Comment by fedeDeb** [comment]
I will take care of it

**Comment by EdwardDunn** [comment]
Completed by @fedeDeb
