### ISSUE TITLE
Idea to use github pages to make the game playable online

### ISSUE THREAD

**Issue by Scruffy21** [EdwardDunn/Platform-Game#105]
It would be cool to make the game online on Github Pages, and put the link to the live site in the repository's description area.

Anyone who wants to try the game could do it without having to download the code.

**Comment by Redarcher9** [comment]
http://jmcglone.com/guides/github-pages/

I found a link to do this.
@EdwardDunn this is really a cool feature you should add it to this repository.

**Comment by EdwardDunn** [comment]
@Redarcher9 @Scruffy21  Great suggestion, i will look into it.

**Comment by EdwardDunn** [comment]
Game is now available at **https://edwarddunn.github.io/Platform-Game**

Thanks @Redarcher9 & @Scruffy21 for this suggestion!

**Note: I have changed the name of JS_game.html to index.html for obvious reasons.
