### ISSUE TITLE
Enhance jump by buttons

### ISSUE THREAD

**Issue by fedeDeb** [EdwardDunn/Platform-Game#108]
I noticed a difference between the jump from the keyboard and the one performed by the buttons on the screen: in this last mode I noticed that the jump is still imprecise, as if you could modulate the height, and is not perfect as performed by keyboard.
I wish I could solve it.

**Comment by EdwardDunn** [comment]
@fedeDeb yes your right they aren't the same. The onscreen buttons are import for mobile users. 

Just let me know if you need any help.

**Comment by fedeDeb** [comment]
I solved the problem, to make them identical, just call the moveUp function in the mouseDown, and remove the mouseUp only for the jump.

I sent the changes, but I think I will not have the new pull request done because it has joined my previous one.

**Comment by EdwardDunn** [comment]
@fedeDeb No problem, i see it in your other PR.

**Comment by EdwardDunn** [comment]
Completed by @fedeDeb
