### ISSUE TITLE
Character doesn't clash with enemies

### ISSUE THREAD

**Issue by fedeDeb** [EdwardDunn/Platform-Game#110]
I think there is an error due to the latest changes.
The character does not clash with the enemies anymore, or am I wrong?
I was about to add my changes (which I did on the old version of the project) but I realized this.

**Comment by mordore4** [comment]
Woops, I added immortality for a second for testing, seems like I forgot getting rid of it :p

**Comment by fedeDeb** [comment]
no problem :)

**Comment by EdwardDunn** [comment]
Fixed
