### ISSUE TITLE
Mirrored image of the character when facing left

### ISSUE THREAD

**Issue by Scruffy21** [EdwardDunn/Platform-Game#112]
I had an idea to change the direction in which the playerCharacter is facing when moving on the screen. That is, face right when moving right, face left when moving left. Using mirrored versions of the original images.

I wrote most of the code already, making some small changes now. If you want this functionality then I will make a PR with it.

**Comment by EdwardDunn** [comment]
@Scruffy21 Yeah good idea, go ahead and submit a PR.

**Comment by EdwardDunn** [comment]
Completed by @Scruffy21
