### ISSUE TITLE
Add a duck feature

### ISSUE THREAD

**Issue by up730418** [EdwardDunn/Platform-Game#115]
This would allow the player to duck under enemies like the one in the screen shot.

![image](https://user-images.githubusercontent.com/12224925/35689252-f2d08006-076a-11e8-8342-1f02404060ec.png)

This could be controlled by pressing the down arrow and an on screen button.
This would also require new images to be designed.

**Comment by EdwardDunn** [comment]
@up730418 Great idea, that would really add to the game play!

**Comment by robatronPrime** [comment]
Hi I would like to contribute to this enhancement.

**Comment by chotuaashiq** [comment]
@EdwardDunn @up730418  I claim this issue

**Comment by up730418** [comment]
@EdwardDunn Can you mark this as up for grabs as i'm unable to complete it at the moment.

**Comment by dilsheen** [comment]
@EdwardDunn Can I take this up?

**Comment by EdwardDunn** [comment]
@dilsheen Yeah go ahead

**Comment by kjesek** [comment]
@dilsheen are you still working on this?

**Comment by nishkt** [comment]
Hi, so i saw that this issue has not been resolved yet. Unless someone has already figured it out, I have found a solution for the ducking of the character. The gif below shows the example of ducking. 
![game-platformgif](https://user-images.githubusercontent.com/11956034/37246878-2ac90b4a-24cb-11e8-8f10-59d0769ab127.gif)

Currently when the DOWN or S button are pressed, the character shrinks to a third of its size. the character is able to jump and move left and right while ducking. The character can also duck while it is jumping. Including the button is a bit difficult for me as the image is not available and I have never touched any photoshop software. Let me know if you would like me to send a PR. If any feedback, let me know as well. Thanks

**Comment by EdwardDunn** [comment]
@nishkt Thanks for attempting the issue. @dilsheen & @kjesek if you're working on this could you let us know. 

I like what you have done for making the character duck, one thing I would suggest is that you can only duck when not in the air (not jumping).

Looks awesome though!

**Comment by nishkt** [comment]
@EdwardDunn Would you want the character to be able to move left/right while ducking? i can take away the option of ducking while jumping for sure. 

I will also make the character half its size when ducking. The current third decrease seems way to small for me.

**Comment by EdwardDunn** [comment]
@nishkt Yes It would be good for the character to still be able to move left and right while ducking.

I agree that half size would be better.

Thanks!

**Comment by nishkt** [comment]
@EdwardDunn So the character is now not able to duck while in the air and is not able to jump while ducking. The character can move left and right. The halfsize duck has been implemented as well. Can I go ahead and send the PR?

**Comment by EdwardDunn** [comment]
@nishkt Yeah go ahead!

**Comment by EdwardDunn** [comment]
Completed by @nishkt
