### ISSUE TITLE
Coin Explode Animation

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#116]
Currently when the player character hits a coin, it simply disappears.

It would look much better if a small exploding animation took place on the coin.

Or for a simple starting solution the coin could change colour before disappearing.

**Comment by nishkt** [comment]
Hi can I take this issue?

To figure this issue, should i try adding the animation in the function updateGameArea() in the for loop where detection with of a player with a coin is made? or should I create a new function called changeCoinStatus and work from there. Which would make it easier to read for future contributors?

**Comment by Edward1505629** [comment]
@nishkt It would be best to create a new function and call it from the updateGameArea function. This would make it easier for other contributors to understand what you piece of code does.

**Comment by nishkt** [comment]
So I didn't exactly make the coins explode. instead created a function called coinDisappear() that would decrease the alpha of the coin and move it upwards by increasing the y-component. Kinda like what happens in Mario. check it out. Let me know if you want me to do anything else. 
![game-platformgif](https://user-images.githubusercontent.com/11956034/36164486-e9df0eb4-1105-11e8-952b-da2efaffa8bf.gif)

**Comment by EdwardDunn** [comment]
@nishkt Great! Looks good and a goes with the Mario theme that the game was originally designed on. Can you submit a PR for the change.

**Comment by nishkt** [comment]
@EdwardDunn Thanks! I submitted my PR for the change. I'm sorry but this is my second PR ever so please let me know if something is wrong and I can redo it.

**Comment by EdwardDunn** [comment]
Completed by @nishkt
