### ISSUE TITLE
Bug: Pausing causes mute symbol to appear

### ISSUE THREAD

**Issue by Germlord** [EdwardDunn/Platform-Game#117]
Currently, pausing the game causes the mute symbol to appear over the sound, even though pausing does not affect whether the game is muted or not.

In theory, the fix should be that the mute button's appearance doesn't change when pausing. It also might be nice to have the pause button itself disappear when paused, since it doesn't have any functionality on the pause screen.

![platformgame_bug_iconerrors](https://user-images.githubusercontent.com/34950441/35896804-d75a6ea2-0b72-11e8-952f-ae95c3d82aa0.jpg)

**Comment by Germlord** [comment]
Update: I believe I've solved the problem with the mute button displaying oddly. Will submit a pull request accordingly.

**Comment by EdwardDunn** [comment]
Completed by @Germlord
