### ISSUE TITLE
Coin sound effect

### ISSUE THREAD

**Issue by ap1459** [EdwardDunn/Platform-Game#126]
Adding a sound-effect to alert the player they have successfully picked up a coin may be beneficial, and I would like to implement this. What are your thoughts @EdwardDunn ?

**Comment by EdwardDunn** [comment]
@ap1459 Sounds like a good addition! Go ahead.

**Comment by Aseged** [comment]
Are you still working on this @ap1459

**Comment by ap1459** [comment]
Hi @Aseged , i've already submitted a pull request, waiting to hear back now.

**Comment by Aseged** [comment]
@ap1459  ok cool, thanks for letting me know

**Comment by EdwardDunn** [comment]
Completed by @ap1459
