### ISSUE TITLE
Add walking and jumping effect to 'good_guy' character

### ISSUE THREAD

**Issue by Aseged** [EdwardDunn/Platform-Game#127]
It would be nice if the character walks as oppose to slide to the left and right. I would like to implement this if you think its a good idea @EdwardDunn . good game

**Comment by EdwardDunn** [comment]
@Aseged Yeah thats a great idea! Go ahead.

**Comment by Aseged** [comment]
@EdwardDunn  I'm sorry I been quiet, I have been preoccupied lately. I will close the open issues assigned to me soon.

**Comment by EdwardDunn** [comment]
@Aseged Closed due to inactivity
