### ISSUE TITLE
Overall design/direction

### ISSUE THREAD

**Issue by Germlord** [EdwardDunn/Platform-Game#132]
At this point, it might be good to discuss what the overall direction of the game is going to be--what kind of end product might we be shooting for? I could see this game evolving into a side-scrolling platformer, or an expanded version of the kind of survival game that it currently is, but it would probably help to have a more concrete idea of what to aim for. Thoughts?

**Comment by EdwardDunn** [comment]
@Germlord I agree that it would be good to have a well thought out direction for the game. 

The aim of the project wasn't to have an end product in sight, more to provide an easy project to contribute to for people new to coding and GitHub.

I think your idea of implementing the side-scrolling platform is what the game needs. If you would like to implement such a feature, let me know.

**Comment by Germlord** [comment]
I'll can try drafting something like that. Fair warning though, it may take me a couple days, so if anyone else wants to try their hand at this they're welcome to do so.
