### ISSUE TITLE
Bug: Pressing Left/Right shortly after jump will "cancel" the jump

### ISSUE THREAD

**Issue by Germlord** [EdwardDunn/Platform-Game#136]
It seems that pressing LEFT or RIGHT shortly after pressing down the UP key will cause a jump cancel. This doesn't seem like the sort of thing we want in game, though, since it makes it easy to accidentally jump INTO an enemy rather than over them. I'm going to see if I can figure it out--if I haven't made a pull request by then end of today (3/2/2018), it's probably safe to put this up for grabs.

**Comment by EdwardDunn** [comment]
Completed by @Germlord
