### ISSUE TITLE
Bug: holding down both left and right movement keys always results in character going right

### ISSUE THREAD

**Issue by Germlord** [EdwardDunn/Platform-Game#138]
This is a bit trickier to explain, so I'll break down the cases.

1. If the user is holding down the LEFT/A keys, and then presses RIGHT/D, the character will start moving right, and will start moving left again if RIGHT/D is released.

2. If the user is holding down RIGHT/D, and then presses LEFT/A, nothing will happen.

The problem here is consistency. In my opinion, it's unintuitive to have the right movement direction be "dominant"--there should be similar effects between the two cases listed above. There are several possible solutions to this, for example, making the character stop moving if both direction keys are held. Personally, I think that it would probably be best if pressing down both movement keys made it so that the character started moving in the direction of the SECOND key pressed--in other words, the same behavior as in case #1 above. This seems like it would feel the smoothest/most intuitive. However, I'd like to hear input before trying to implement a final solution.

**Comment by EdwardDunn** [comment]
@Germlord I agree that making the character move on the second key press makes most sense.

**Comment by EdwardDunn** [comment]
Completed by @Germlord
