### ISSUE TITLE
Dynamic background

### ISSUE THREAD

**Issue by dezcore** [EdwardDunn/Platform-Game#141]
Dynamically move background while playerCharacter is moving.
I implemented it and i have this result : 

![demo](https://user-images.githubusercontent.com/36500163/37197343-be5d41a2-237a-11e8-8de9-1d2d24773efd.gif)

What do you  think about this idea @EdwardDunn ?

**Comment by EdwardDunn** [comment]
@DesseKande Looks great! Issue #132 has suggested implementing this. @Germlord have you started the side scrolling screen or can @DesseKande issue a PR for it?

**Comment by Germlord** [comment]
@EdwardDunn @DesseKande 
No no that looks great, please go ahead and open that pull request.

**Comment by EdwardDunn** [comment]
Completed by @DesseKande
