### ISSUE TITLE
Highscore widget

### ISSUE THREAD

**Issue by Redarcher9** [EdwardDunn/Platform-Game#146]
I was thinking of adding a Highscore text at the top of the screen somewhere around the text which displays the current score. The solution I could think of is by creating a new array which stores the final scores of the current session and a new function which computes the maximum score and displays it. Can I start working on this? Can you think of any other way to make it work?

**Comment by EdwardDunn** [comment]
@Redarcher9 that's a great idea.

I think your solution sounds good, perhaps make it obvious that the score is the users highest score 'your highest score'.

Let me know if you need any help.

**Comment by Redarcher9** [comment]
I tried to update my fork with the update instructions provided in the contributions.md file.But,the repository in my profile still says 'This branch is 2 commits ahead, 7 commits behind EdwardDunn:master'.

**Comment by EdwardDunn** [comment]
@Redarcher9 make sure you have the upstream repo as your remote.

'git remote -v' will show this.

**Comment by EdwardDunn** [comment]
Completed by @Redarcher9
