### ISSUE TITLE
New HUD

### ISSUE THREAD

**Issue by painlibanais** [EdwardDunn/Platform-Game#147]
I thought back to a new user interface, I'd like to know if it's a good idea @EdwardDunn ?

![screen shot 2018-03-13 at 18 29 25](https://user-images.githubusercontent.com/35867791/37359000-c52dc6da-26ec-11e8-938c-9441de6fbfc5.jpg)

**Comment by EdwardDunn** [comment]
@painlibanais Great idea!

Another contributor is in the process of adding a high score element, would you mind adding this also when he submits his PR? This will be within the next couple days, I will let you know.

**Comment by EdwardDunn** [comment]
@painlibanais Thats the high score functionality implemented.

If you could add this to your new interface that would be great.

**Comment by painlibanais** [comment]
I'm sorry for taking time to respond, i was little busy. I work on it right now.

**Comment by EdwardDunn** [comment]
Completed by @painlibanais
