### ISSUE TITLE
Reduce level 1 completion score

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#15]
The first level completes when the score counter reaches 11000, this is too high because it takes a long time to get to this score. Reduce this to 5000.

This is the code that stops the game once the score counter reaches 11000 (in script.js file).

//when frame number reaches 11000 (point at which obstacles end) end game
  if (myGameArea.frameNo == 11000){
  alert("CONGRATS YOU HAVE ESCAPED ALL THE BAD GUYS, PHEW! PRESS START TO TRY AGAIN");
  myGameArea.stop();
  }

Just change 'myGameArea.frameNo == 11000' to 5000.

**Comment by Redarcher9** [comment]
Hi I am a beginner and I would like to work on this. Can you help me get started with this?

**Comment by EdwardDunn** [comment]
@Redarcher9 Thanks for your interest! If you have a look at the contributing guide file included in the project it will give you steps on how to get started. 

If you need help with anything just leave a comment.

**Comment by Redarcher9** [comment]
i corrected the code,followed all the 11 steps listed in your contributions.md page.Did you get any pull request?

**Comment by EdwardDunn** [comment]
@Redarcher9 Well done that worked great! I have merged the PR.
