### ISSUE TITLE
Add duck feature in instruction modal

### ISSUE THREAD

**Issue by nishkt** [EdwardDunn/Platform-Game#150]
Hey guys. the duck feature is activated when the user presses 'S' or 'DOWN'. This needs to be added to the instruction modal. Additionally, a 'DUCK' button needs to be available on the screen during gameplay. n

**Comment by EdwardDunn** [comment]
@nishkt good spot about adding the button, I didn't think of that.

**Comment by Germlord** [comment]
I'll work on this one today.

**Comment by Germlord** [comment]
Alright, update: wasn't able to figure out how to make a devoted button image for this. The instructions have been updated, but the button'll need to be added by someone else, sorry.

**Comment by EdwardDunn** [comment]
@Germlord No problem, thanks for updating the instructions!
