### ISSUE TITLE
Smoother transitions between levels

### ISSUE THREAD

**Issue by wwatkins09** [EdwardDunn/Platform-Game#152]
Right now the transition from one level to another is very abrupt, especially if you aren't looking at the countdown clock. Would it be possible to add some sort of modal showing that you beat the level, and maybe even the amount of points you gained from that particular level? I'd be glad to open a PR for it.

**Comment by EdwardDunn** [comment]
@wwatkins09 Great idea, perhaps the modal could be on a timer so that it displays for 3 seconds before opening the new level.

Any issues just leave a comment.

**Comment by EdwardDunn** [comment]
Completed by @wwatkins09
