### ISSUE TITLE
Make clouds pop in continue

### ISSUE THREAD

**Issue by painlibanais** [EdwardDunn/Platform-Game#157]
I would like to add clouds in continuous. Currently, the clouds are just at the beginning of the level, I would like to make them appear continuously on the whole level @EdwardDunn 
![platforme](https://user-images.githubusercontent.com/35867791/37716150-1bc91a94-2d1e-11e8-900c-0b00ea945d5e.gif)

**Comment by EdwardDunn** [comment]
@painlibanais That is a good idea. This has happened due to the new scrolling background.

Just leave a comment if you need any help.

**Comment by Germlord** [comment]
I've already handled this one, actually. Should be solved in Pull Request #151 when that's finalized. Good work catching this, though.

**Comment by EdwardDunn** [comment]
Completed by @Germlord.

@painlibanais feel free to think of new issues to create, thanks for your input.
