### ISSUE TITLE
Add settings button

### ISSUE THREAD

**Issue by dezcore** [EdwardDunn/Platform-Game#162]
Give the possibility to choose keys.
![options](https://user-images.githubusercontent.com/36500163/37809948-e9e0f26a-2e51-11e8-8a9d-a759e69cef9b.jpeg)
What do you think about this idea @EdwardDunn ?

**Comment by EdwardDunn** [comment]
@DesseKande Thats a cool idea!

**Comment by EdwardDunn** [comment]
Completed by @DesseKande
