### ISSUE TITLE
game over message at the begining

### ISSUE THREAD

**Issue by Redarcher9** [EdwardDunn/Platform-Game#17]
When i open the html file,the browser says game over.I think there should be a start button or something like that to start the game.There's a broken file symbol at the top left corner of the canvas.
![screenshot from 2017-08-22 17-35-14](https://user-images.githubusercontent.com/19843336/29564636-5222cf4a-8760-11e7-8ce5-ecc0269cb5a4.png)

**Comment by EdwardDunn** [comment]
@Redarcher9 Thanks for letting us know about your issue. I haven't experienced this problem and i am unable to replicate it. Does this happen if you use a different browser?

**Comment by Redarcher9** [comment]
Yes it happens with chromium too. Does it have anything to do with Linux? Do I need to install dependencies to run this?

**Comment by EdwardDunn** [comment]
@Redarcher9 Are you using Ubuntu? Can you try it with Firefox?

**Comment by Redarcher9** [comment]
This works fine on windows i just tested it.
Doesnt works on ubuntu,the screenshot attached to the first comment was taken from firefox browser.

**Comment by EdwardDunn** [comment]
@Redarcher9 Thanks for testing it on windows. It must be a file association issue of some sort. Let me look in to this.
