### ISSUE TITLE
Functionality: No duck button is presented on-screen

### ISSUE THREAD

**Issue by Germlord** [EdwardDunn/Platform-Game#170]
Currently, there is no duck button (unlike the jump, left, and right buttons) on-screen. If anybody knows the source where we got the other three button images from, that would be an ideal place to a duck button image from.

**Comment by EdwardDunn** [comment]
@Germlord it is fairly easy use the existing buttons to create a new one in most editors like paint or Photoshop.

**Comment by Booxworm** [comment]
Tried to do a duck button, but didnt know which font was it so it looks kind of different
<img width="76" alt="jump" src="https://user-images.githubusercontent.com/38198099/38652055-d4b27d9c-3e36-11e8-8a76-c22ab2f940ca.png">
<img width="76" alt="duck" src="https://user-images.githubusercontent.com/38198099/38652020-b606f8fa-3e36-11e8-9f04-08d4168f1409.png">

**Comment by EdwardDunn** [comment]
@Booxworm That looks good!

**Comment by Booxworm** [comment]
Tweaked it a bit to make it look better.
#177 

![jump](https://user-images.githubusercontent.com/38198099/38774278-a25cae22-4097-11e8-9053-2c4f0f63cb4b.png)
![duck](https://user-images.githubusercontent.com/38198099/38774277-9f836006-4097-11e8-9a51-595e7938801c.png)

**Comment by EdwardDunn** [comment]
Completed by @Booxworm
