### ISSUE TITLE
Jump button can be manipulated

### ISSUE THREAD

**Issue by Redarcher9** [EdwardDunn/Platform-Game#19]
when jump button is pressed,the main character(hero) flies and the character comes down only when the button is released.I think there should be some time constrain for which the player can stay up in the air

**Comment by EdwardDunn** [comment]
@Redarcher9 Great suggestion! You could try adding a time constraint or change the button controls to only fire once on key press (rather than continuously jumping if you hold the key down). Try experimenting and let us know what you think.
