### ISSUE TITLE
Enhance game over display

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#21]
When the main character collides with an enemy, the game is over. A display message shows to prompt the user to restart the game.

![game_over_screenshot](https://user-images.githubusercontent.com/22660271/29995083-a0a626c8-8fd8-11e7-8f2f-7ddbe8ff4da9.PNG)

This display is a bit plain, it would be better if it fit the styling of the game more. 

Any questions or ideas, post a comment.

**Comment by iamstratos** [comment]
I could help with this one :)

**Comment by EdwardDunn** [comment]
@iamstratos Great! When you are ready to submit your work, create a new Pull Request. Thanks for contributing.
