### ISSUE TITLE
Create 3rd level

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#27]
Currently there are two levels in the game. Add a third with a new background and enemy character.

The level is created by adding a new level function in the Game.js file.
![image](https://user-images.githubusercontent.com/22660271/30609503-7c9a1d7c-9d73-11e7-847e-26e335a74680.png)

Remember to add a new if statement for startLevel3() in the UpdateGameArea function

![startlevel2_snippet](https://user-images.githubusercontent.com/22660271/30609626-d6321308-9d73-11e7-92e1-03212d736b23.PNG)

Any suggestions or issues, just leave a comment!

**Comment by brissettdwayne** [comment]
I will work on creating a 3rd level for the game.

**Comment by EdwardDunn** [comment]
@brissettdwayne Great! Let me know if you need any help.
