### ISSUE TITLE
Create bonus obstacles 

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#30]
**Bonus Obstacles**

Currently the game only consists of jumping over enemy characters, the longer you stay alive the higher your score.

An additional feature could be to have bonus obstacles appear with the enemy characters, if you jump on them you get a certain amount of points added to your score.

If you need help or have any suggestions, just leave a comment.

**Comment by treyhboy** [comment]
hey! I would like to work on adding the above feature

**Comment by EdwardDunn** [comment]
@treyhboy great! You could add a bonus enemy character that explodes when jumped on and adds extra points to the score.

There may be a but of work in this so if you want to add a simplified version first, that would be fine.

**Comment by treyhboy** [comment]
@EdwardDunn I am working on the basic one first than i will update it further if i can
