### ISSUE TITLE
Add animated background

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#32]
**Add animated background**

Currently the backgrounds is a still image, it would be good if some parts where animated. An example of this would be to have moving clouds or rain. This could be done by adding extra components into the game, or you could look for copyright free backgrounds that already have some kind of effects.

Try changing the level 1 background first.

If you have any suggestions or need any help, just leave a comment.

**Comment by ghost** [comment]
I would like to take care of this as a first timer

**Comment by EdwardDunn** [comment]
@Ginger90 Great! Just leave a comment if you need any help.

**Comment by arjbholu** [comment]
I am also working on this issue. I have made this type of cloud:
![screenshot from 2017-10-29 10 33 39](https://user-images.githubusercontent.com/8599981/32140836-c5adf872-bc94-11e7-9575-40423324a408.png)
Is that fine?

**Comment by EdwardDunn** [comment]
@arjbholu That's fine to work on this issue. Your addition looks good, when you are ready create a new PR.
