### ISSUE TITLE
Animate player character

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#35]
**Animate player characters**

Currently the main characters are just single images. It would be good to animate the character so that when they move their position changes e.g. in a running stance. Currently there are two different player characters in the game for levels one and two. The images have been taken from sprite sheets available at;

http://www.gameart2d.com/temple-run---free-sprites.html
http://www.gameart2d.com/adventurer-girl---free-sprites.html

These sheets have lots of other stances of the character that could be incorporated in to the game.

If you have any questions or suggestions just leave a comment.

**Comment by SnGrimes** [comment]
Could I work on this as a first timer?

**Comment by EdwardDunn** [comment]
@SnGrimes Great, just leave a comment if you need any help!

**Comment by SnGrimes** [comment]
The male character is running in a test page. I'm looking at how to implement animations in the main game.js file. Any suggestions?

**Comment by EdwardDunn** [comment]
@SnGrimes Hey sorry for the late reply. Try looking at the web page that the main character image comes from (this can be found in the copyrights file). This site contains a sheet of lots of different character positions. The best way to create an animation is to make the image change when a key is pressed. For example, when the right key is pressed the character image changes to a running stance.

Hope this helps!

**Comment by SnGrimes** [comment]
I'm sorry I wasn't clear. The male sprite is already animated. The character is running in his own canvas object in a test page. Right now I'm trying to figure out how to integrate his animated run into the game.  I found this [link](http://jlongster.com/Making-Sprite-based-Games-with-Canvas) and will try a separate sprite.js file to add animations into the game. If you have any suggestions about where to add the animation code in the Game.js file that would help me a lot.

**Comment by EdwardDunn** [comment]
@SnGrimes Can you show me your code so far? Just copy and paste it in a comment.

**Comment by SnGrimes** [comment]
I created the` loadResources()` function to load the images into an array for animating and put `loadResouces()` under the startGame() function. I originally put it in a IIFE in the Game.js file but that just blew everything up.

`function loadResources() {
    var maxFrames = 9;
    for (let x = 0; x < maxFrames; x++ ) {
        let img = new Image();
        img.src = "Pictures/Sprite Sheets/Idle__00" + x + ".png";
        idleArray.push(img);
    }
}`

I put this `animate()` function under the `this.update` function under component and ran it under the if state for image. This prevented the player character and monsters from spawning and the game eventually skips to level 2.

`function animate() {
ctx.clearRect(this.x, this.y, this.width, this.height);
            var msPerImg = 100;
            var currentTime = new Date().valueOf();
            var idleToDraw = this.image[Math.floor(currentTime/msPerImg) % this.image.length];
            ctx.drawImage(idleToDraw, this.x, this.y);`

I've never had to squeeze code into an existing program like this before so I'm a bit lost.

**Comment by EdwardDunn** [comment]
@SnGrimes Thanks for putting your code up. HTML canvas starts to get difficult when you want to draw new components during run time. The easiest solution is to manipulate existing ones.

You could start by creating a function that loops through each of your sprite images using a timer,

function animatePlayerCharacter(){		

	//Timer, set this to the frame rate you want
	var timerInterval = setInterval(spriteTimer, 1000);
	
	var spriteImageCounter = 1;
	
	//This would be the number of sprite images you have, 10 is just an example
	var numberOfSpriteImages = 10;

	function spriteTimer(){
			
		if(spriteImageCounter < numberOfSpriteImages){
		
			//If you named each sprite good_guy1.png, good_guy2.png, good_guy3.png etc.....
			playerCharacter.image.src = "Pictures/good_guy" + spriteImageCounter + ".png";	
			
			spriteImageCounter++;
		
		}
		else{
			
			//Reset back to the beginning 
			sprinteImageCounter = 1;
			
		}

	}	

}	

You would need to call this when a key is pressed or on screen button. When the key or button is released reset the image.

This is just one way of doing it, feel free to try other methods but hopefully this helps you move forward.

**Comment by EdwardDunn** [comment]
@SnGrimes An alternative would be to use a JQuery plugin. There are a number of different ones available this one might help - http://blaiprat.github.io/jquery.animateSprite/. Remember if you use any existing software, check the license and add it in to the README.txt file.

**Comment by SnGrimes** [comment]
Thank you! I will look at that one and some other plugins tonight.

**Comment by SnGrimes** [comment]
Welp, I've created a working running animation with just a difference in one line of code.
This code will create a smooth running animation with an even frame rate but the animation will not stop.
`function animatePlayerCharacter () {
    var currentTime = new Date().valueOf();
    var requestID;
    var frames = 9;
    var spriteImageCounter = Math.floor(currentTime/100) % frames;
    var toDraw = playerCharacter.image.src = "Pictures/Sprite_Sheets/Run__00" + spriteImageCounter + ".png";
}`

Once I remove `requestAnimationFrame(animatePlayerCharacter);` The animation will stop once the arrow key is released but the animation is uneven and not very smooth. 
I checked some of the animation libraries and they will either use a separate canvas object or animate a div background. I'm going to keep looking for a solution but any help would be appreciated.

**Comment by EdwardDunn** [comment]
@SnGrimes Could you post your code for the requestAnimationFrame() method?

I agree that using the libraries is difficult because creating multiple canvasses is tricky. A simple solution is best here.

**Comment by SnGrimes** [comment]
Here is the documentation for requestAnimationFrame.
https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

**Comment by EdwardDunn** [comment]
@SnGrimes Sorry for the delay in getting back to you. Could you create a new PR request with your work so far? That way I can see exactly what code you have added.
