### ISSUE TITLE
Create 4th Level

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#36]
**Create 4th Level**

Currently there are three levels in the game. Add a fourth with a new background and enemy character.

The level is created by adding a new level function in the Game.js file (See startLevel2() function as an example).

Remember to add a new if statement for startLevel4() in the UpdateGameArea function

if (gameArea.frameNo === 3000){
   gameArea.stop();
   currentLevel++;

   if(currentLevel === 2){
	startLevel2();
   }
   else if(currentLevel === 3){
      startLevel3();
   }
   else{
       gameComplete();
   }

}

Any suggestions or issues, just leave a comment!

**Comment by treyhboy** [comment]
A would like to work on this one @EdwardDunn 
As a extended difficulty i think varying the speed of different enemy character should be a good idea
For example-enemy 1 would be coming with speed v1 and enemy 2 with v2
if u had anything else in mind kindly suggest  :)

**Comment by EdwardDunn** [comment]
@treyhboy Yeah good idea!

**Comment by EdwardDunn** [comment]
@treyhboy Completed
