### ISSUE TITLE
Enhance player character jump

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#37]
**Enhance Player Character Jump**

Currently the player character moves around the screen fine. However the jump function is still a bit slow and laboured. It would be good if it was more like other traditional platform game character jumps. 

Watch this video as an example of what i mean.
https://www.youtube.com/watch?v=Q8ivkP-qs04

Any questions or suggestions just leave a comment.

**Comment by Redarcher9** [comment]
You want a diagonal jump?

**Comment by Redarcher9** [comment]
You can do it using right and up arrow simultaneously.

**Comment by EdwardDunn** [comment]
@Redarcher9 It could be good to adjust the jump settings so that every jump is slightly diagonal.

**Comment by Scruffy21** [comment]
I think the player has too much control over how high the jump is. It's almost as if the character was levitating.

**Comment by EdwardDunn** [comment]
@Scruffy21 The player movement was originally planned to be like the old Mario style platform games, however it isn't quite there yet. Feel free to play around with the jump and left/right movements to see if you can get a better game play. 

Thanks for you contributions so far, the game is making good progress.

**Comment by Scruffy21** [comment]
I'm trying to make sense of it now. It isn't easy...

**Comment by fedeDeb** [comment]
I'm also trying to solve this problem, and I think I'm on the right track. I'll keep you informed.

**Comment by Scruffy21** [comment]
Then I'll leave it to you since I didn't have much time lately to think of it. If you need some help let me know.

**Comment by fedeDeb** [comment]
I think I have improved the jump of the character, I'll do tomorrow  a pull request to show you the result. I hope I have done a good job

**Comment by EdwardDunn** [comment]
@fedeDeb Great, i will take a look at it when you submit it.

**Comment by EdwardDunn** [comment]
Completed by @fedeDeb
