### ISSUE TITLE
Exploding obstacles with bonus score

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#39]
**Exploding Obstacles**
 
A good addition to the game would to have objects that appear in the same way the enemy characters do, but these objects give you extra points to your score if you jump on them. 

These objects could also explode to show the player has successful hit them.

If you need any help or have a suggestion, just leave a comment.

**Comment by ShaneWalsh** [comment]
I would like to take a stab at this as a first timer.

**Comment by EdwardDunn** [comment]
@ShaneWalsh Great, just leave a comment if you need any help.

**Comment by ShaneWalsh** [comment]
I think this change has a dependency on #35  since if we want to animate the explosion we can probably reuse the same code from #35 
So I am no longer working on this issue. I have idea for another issue though, so ill create an issue for it.
