### ISSUE TITLE
Change player characters image

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#4]
Choose a new higher resolution image for the main character. This can be any copy-right free image but try to keep it the same overall size as the original. Remember to update the Copyrights file with the source of the image added.

![image](https://user-images.githubusercontent.com/22660271/29169667-1c2c78ce-7dcd-11e7-9fce-d0e1b0c589e9.png)

**Comment by krupam** [comment]
Hi, 
I am a first-timer. I would love to work on this project.

**Comment by EdwardDunn** [comment]
@krupam Thanks for your interest. 

Best place to start is by at looking the [Contributing Guide](https://github.com/EdwardDunn/Platform-Game/blob/master/Contribution_Guide.md).

Fork the repo and get to know how the project works, then try making a contribution.

I will assign this issue to you!

**Comment by krupam** [comment]
@EdwardDunn Thank you! I am excited to work on this.
