### ISSUE TITLE
Make Enemies Killable by jumping on their heads, and adding to the score.

### ISSUE THREAD

**Issue by ShaneWalsh** [EdwardDunn/Platform-Game#40]
I think it would make the game more interesting if you could element the bots instead of simply avoiding them.

I will work on this code. and create a PR, if the project doesn't want to go this way just let me know.

**Comment by ShaneWalsh** [comment]
Changed score to scoreBoard.
Added score variable to gameArea to track the score. 
Added method to increment score, isolating point of change.
Added increment frameNo method. (frameNo is no longer used, but frame rate may be used later so i didnt remove it)
Added new method to test for player jumping on bots. 
Added new alive variable to componets, so you can setAlive(false) when a bot is killed and collision detection and stop working for that bot, so you can kill it and be killed by it at the same time.
Ideally killed bots would play some sort of death animation, but we dont have animation support yet, so for the moment I just make them drop out of the screen.
When a bot is killed, score is increased by 100.
Tested the changes, played the game through in Chrome, Win 8. 

Created a PR.

**Comment by EdwardDunn** [comment]
@ShaneWalsh Well done!
