### ISSUE TITLE
Highlight Bonus Score

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#42]
**Highlight Bonus Score**

A new feature recently added allows the player to kill enemy characters by jumping on them. As a bonus, the player gets 100 extra points added to their score.

It would be good to highlight this bonus. Make the score light up (change colour) for a few seconds to show the player has received the bonus.

If you have any suggestions or need any help just leave a comment.

**Comment by brodyf42** [comment]
I'd like to take this one.

**Comment by EdwardDunn** [comment]
@brodyf42 Completed
