### ISSUE TITLE
New Name Suggestions?

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#43]
**New Name**

It would be good to give the game a name (rather than just platform-game).

Leave a comment if you have a suggestion or if you like someone else's suggestion.

**Comment by skywalker212** [comment]
what is this game about?
it would be easier to give it a name if I knew little more about it 😅

**Comment by EdwardDunn** [comment]
@skywalker212 Hey, clone the repo and play the game. This will give you an idea of what the game is.

**Comment by skywalker212** [comment]
okay!

**Comment by skywalker212** [comment]
The Good, The Bad and The Jumping
how about we come up with the caracter's name?
so we can have a better name.

**Comment by EdwardDunn** [comment]
@skywalker212 Thanks for the suggestion. Feel free to come up with a character name, there may be a need for it in the future.

**Comment by natyling** [comment]
How about Jump Or Die?  I know character names can help in the overview of the game but I feel it is simple enough to come up with a name right away.

**Comment by skywalker212** [comment]
how about Zombing 
or Zombie Jumping?

**Comment by AdamTheWizard** [comment]
The Jumping Dead sounds cool! like The Walking Dead lol

**Comment by EdwardDunn** [comment]
@AdamTheWizard Yeah the Jumping Dead is a good suggestion.

**Comment by EdwardDunn** [comment]
If anyone has any final suggestions, post them. At the start of next week two names from the suggestions will be chosen and users can vote for which one they want.

**Comment by EdwardDunn** [comment]
**Please add a thumbs up to this post if you prefer THE JUMPING DEAD as a name for the game**

**Comment by EdwardDunn** [comment]
**Please add a thumbs up to this post if you prefer ZOMBIE JUMPING as a name for the game**

**Comment by govindbalaji-s** [comment]
Jumping Dead 👍

**Comment by EdwardDunn** [comment]
**The Jumping Dead has been chosen, thanks for the suggestions!**

**Comment by AdamTheWizard** [comment]
Lol no worries! Happy to help!
