### ISSUE TITLE
Game Instructions Modal

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#44]
**Game Instructions Modal**

When the game first opens it would be good to have an html modal popup with some instructions on how to play the game, like the following.

**How to play the game**
- Complete each level by avoiding the enemy characters
- You can kill the enemy by jumping on them
- Killing them also adds a bonus to your score

**Controls**
- On screen buttons
- Keyboard arrows

If you need help creating a modal this is a good reference 
https://www.w3schools.com/bootstrap/bootstrap_modal.asp

**Comment by JorgeAndd** [comment]
I will work on this one :)

**Comment by EdwardDunn** [comment]
@JorgeAndd Great, let me know if you need any help.

**Comment by JorgeAndd** [comment]
@EdwardDunn I created the modal and some logic to show it only at the first start of the game.
I don't have images for the title or the button, should I push it as it is and maybe open another issue for new images?

![instructions](https://user-images.githubusercontent.com/5915194/31418963-602a74e6-ae0f-11e7-9ebd-eaf297f9b94a.jpg)

**Comment by EdwardDunn** [comment]
@JorgeAndd Looks good! Yeah go ahead and create a new pull request and i will create new issues for the images.

**Comment by EdwardDunn** [comment]
@JorgeAndd Completed
