### ISSUE TITLE
Player Moving After Restart Button Pressed (Intermittent)

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#47]
**Player Moving After Restart Button Pressed (Intermittent)**

There is an intermittent fault with the restart button, when pressed in quick succession the player character continually moves to the right. 

A way to replicate this bug is to end the game by hitting an enemy character, press restart and then quickly hit an enemy again.

**Comment by maanvin** [comment]
@EdwardDunn Has this been fixed? When I played the game several times, I didn't come across the above mention problem. When restart is clicked the player goes back to the starting position and when spacebar is pressed, the game ends with the instructions popping up to start a new game.

**Comment by maanvin** [comment]
oh i just checked....the player moves after clicking restart when the controls on the screen instead of the keyboard are used

**Comment by EdwardDunn** [comment]
@maanvin You're right, it is just with the on screen buttons.

**Comment by saig214** [comment]
@EdwardDunn I have fixed this issue... can I make a pull request?

**Comment by EdwardDunn** [comment]
@saig214 this issue has been assigned to @maanvin. Please allow time for this member to work on this issue. Alternatively you can open your own issues for any new additions you want.

**Comment by saig214** [comment]
@EdwardDunn okay. I was under the impression that the bug was unassigned. Can you tell me how to find if an issue is open or assigned?

**Comment by maanvin** [comment]
@saig214 I was working on the sounds hence I haven't started working on this issue. You can go ahead and add it.

**Comment by saig214** [comment]
@maanvin thank you
@EdwardDunn Can I send a PR?

**Comment by EdwardDunn** [comment]
@saig214 Yes go ahead.

**Comment by EdwardDunn** [comment]
@saig214 Completed
