### ISSUE TITLE
Create Play Button for Instructions Modal

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#48]
**Create Play Button for Instructions Modal**

Currently the instruction modal is using the restart button image for starting the game

![instructions_modal_button](https://user-images.githubusercontent.com/22660271/31488026-599ecc32-af34-11e7-963a-3f749aefe17e.PNG)

Create a new Play button, you can use the existing button images as a template. These can be found in the pictures folder.

Just leave a comment if you have any suggestions or need any help.

**Comment by steflk** [comment]
I'd like to take this one, thanks

**Comment by EdwardDunn** [comment]
@steflk Completed
