### ISSUE TITLE
create level 5 

### ISSUE THREAD

**Issue by treyhboy** [EdwardDunn/Platform-Game#51]
Creating new level with multiple enemy with multiple skills and new player character would be good enhancement to game
i would be happy to contribute to this if you allow me to @EdwardDunn

**Comment by EdwardDunn** [comment]
@treyhboy Great idea!

**Comment by fedeDeb** [comment]
I would like to solve this problem if there is still the possibility @EdwardDunn

**Comment by EdwardDunn** [comment]
@fedeDeb Yeah good ahead I think @treyhboy is no longer working on the issue.

Just leave a comment if you need any help.

**Comment by fedeDeb** [comment]
ok, thank you!

**Comment by fedeDeb** [comment]
I have seen that the part in which the enemies are generated in each level and assigns a type is a bit messy. Can I change the code, using a switch case to improve its understanding? I think of assigning to a variable the number generated by Math.floor (Math.random * number of enemies) and using it as a switch condition.

**Comment by EdwardDunn** [comment]
@fedeDeb The Game.js file is needing a significant update to a more Object Orientated style. Feel free to make changes that reduce code duplication and make the code more readable. Please add in suitable comments and use clearly understandable names for any new variables.

Thanks for your contribution!

**Comment by fedeDeb** [comment]
I think I'm ready to make a pull request.
This is my first contribution, I hope not to make trouble!

**Comment by EdwardDunn** [comment]
@fedeDeb Great, I will look at your PR tomorrow and get back to you.

**Comment by EdwardDunn** [comment]
Completed by @fededeb
