### ISSUE TITLE
Bonus Stars or Coins

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#57]
**Create Bonus Star/Coin Objects**

Like in many old platform games, the player can gain extra points by collecting stars or coins.

![mario-coins](https://user-images.githubusercontent.com/22660271/32024503-b27e7fe6-b9d4-11e7-8739-665b8ef50f91.PNG)

Create a new component that works in a similar way to the enemy characters, but when the player character collides with them they get extra points.

The extra points should be shown as a star/coins total next to the level score. This is a new feature that will be used later to provide a leader board for players (rather than just getting to the end of without dying).

If you need any help or have a suggestion just leave a comment.

**Comment by RichardBoell** [comment]
I'm working on this one as my first contribution!

**Comment by EdwardDunn** [comment]
@RichardBoell Great! Just leave a comment if you need any help.

**Comment by EdwardDunn** [comment]
Completed by @RichardBoell
