### ISSUE TITLE
Main character collision occurs too early

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#6]
When the main character hits an enemy horizontally, the collision is activated too early i.e. the main character image does not actually look like it hit the enemy. This is most likely an issue with the images used for the characters.

![objectcollision](https://user-images.githubusercontent.com/22660271/29169643-f23c1d08-7dcc-11e7-9b5e-6f5bc6a60f65.PNG)

**Comment by kyxap** [comment]
![img](https://content.screencast.com/users/kyxap/folders/Jing/media/cbcfad7f-469a-427e-b6c7-8b0bd962d456/00000067.png)

Is not a bug, the main character has a big hat and its looks like it was not a hit but it really was.
Those objects represented as square so with this realization my suggestion is change the good-guy img.
🌟

**Comment by EdwardDunn** [comment]
@kyxap Yeah i think a new image should be used or cut out the original so that it is not square. If you choose to change the image only use copyright free and update the copyrights.txt file. 

Thanks for your contributions!
