### ISSUE TITLE
Proposal to change scoring scheme

### ISSUE THREAD

**Issue by nealkarpe** [EdwardDunn/Platform-Game#62]
I feel that the scoring scheme is kinda flawed in the sense that at the end of the game, the user does not get a total score accumulated through the entire course of the game. Also I feel like the score should depend upon the time elapsed + the number of enemies killed. My proposal is to change the levels to be for a certain amount of time (eg. 30 seconds), and add score as enemies are killed. Of course, the user will also be awarded points for surviving the duration of the level. Please assign this issue to me if you feel like there is some value in changing the design choice to this! :smiley:

**Comment by nealkarpe** [comment]
Also, following this scheme, coins could be available for adding to the score (as pointed out in another issue). This could be another feature to be implemented in the future!

**Comment by EdwardDunn** [comment]
@nealkarpe Great idea, I think that would really aid the game play of the game.

**Comment by Germlord** [comment]
Working on this issue. It looks like enemies and coins already boost score, so my change was making it so that score is persistent from level to level.

**Comment by EdwardDunn** [comment]
Completed by @Germlord
