### ISSUE TITLE
Inconsistent screen after game ends when clicked outside the modal

### ISSUE THREAD

**Issue by arjbholu** [EdwardDunn/Platform-Game#66]
When a game has ended, if a user clicks outside the modal, an inconsistent screen comes up.
![screenshot from 2017-11-01 19 58 37](https://user-images.githubusercontent.com/8599981/32279800-b416adfe-bf3f-11e7-8b09-f6e4b4604ced.png)
When clicked outside the light brown box, this shows up. Then only option is to reload.
![screenshot from 2017-11-01 20 00 28](https://user-images.githubusercontent.com/8599981/32279835-cd8e4f26-bf3f-11e7-9bde-0ce639e085da.png)

**Comment by EdwardDunn** [comment]
@arjbholu Good spot, I haven't seen that bug before. The current game state must be initialising too soon.

**Comment by EdwardDunn** [comment]
Completed by @arjbholu
