### ISSUE TITLE
Add Restart Button to Game Page

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#68]
**Add Restart Button to Game Page**

Currently the restart button only appears on the game over modal. Add this button to the main game page, this will allow users to restart the game at any time.

![platform_game_screenshot](https://user-images.githubusercontent.com/22660271/32391968-d2f644ea-c0cb-11e7-81ef-1d880cbfa6ab.PNG)

If you require any help or have a suggestion, just leave a comment.

**Comment by govindbalaji-s** [comment]
Can I take this issue up?
Let me clarify myself:
So first I have to add the button for restart in buttonWrapper in html part.
And I should make the event Handlers handle that by calling startGame(). Did I miss anything?

**Comment by govindbalaji-s** [comment]
Done. I have opened PR #69

**Comment by YanniD** [comment]
Hi , this should have been fixed . Did a push just now (I"m new to git so i hope i did it right).
