### ISSUE TITLE
Create Game Name Banner

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#70]
The name of **The Jumping Dead** has been chosen for the game. To illustrate this a banner needs to be created and displayed above the game screen.

Feel free to experiment with the image but try to make it fit in with the game. This task is specifically to create a good banner so try and be imaginative.

![platform_game_screenshot2](https://user-images.githubusercontent.com/22660271/32674212-3fc25eb4-c64a-11e7-900c-a374c5c374ee.png)

If you have any questions or need help just leave a comment.

**Comment by ShrutiArya96** [comment]
Working on this issue.

**Comment by asas2016SEC** [comment]
the logo can be totally selfmade?

**Comment by asas2016SEC** [comment]
Just added a logo in the game please check.

**Comment by ghost** [comment]
I'd like to work on this...

**Comment by EdwardDunn** [comment]
@rurangana Great go ahead, I don't think @AanjaneyaSinghDhoni is working on this anymore.

**Comment by smithmich12** [comment]
If you haven't found what you're looking for I am willing to take a shot at it.

**Comment by EdwardDunn** [comment]
Completed by @smithmich12
