### ISSUE TITLE
Named constants

### ISSUE THREAD

**Issue by govindbalaji-s** [EdwardDunn/Platform-Game#72]
I recently tried to scale down the canvas a bit, but that was an epic failure even though I changed the 400 to 375 at all places. The jump control which depended on it froze because of it. I feel code will be easy to update further changes if it is refactored with named constants in place of raw ones.

**Comment by EdwardDunn** [comment]
@govindbalaji-s Yes all constants should be easily visible. Use the naming convention of all constants in uppercase e.g. GAMELEVEL.

**Comment by govindbalaji-s** [comment]
I am sorry that I would be caught up in the school and cant be very active. I think this issue might get fixed sooner if someone else takes this up.

**Comment by EdwardDunn** [comment]
@govindbalaji-s No problem, thanks for letting people know.
