### ISSUE TITLE
GAME PAUSE!!

### ISSUE THREAD

**Issue by aki-sud** [EdwardDunn/Platform-Game#73]
The game can only be restarted and not paused right now.Hence, I would like to take up this issue so that the game can be paused.

**Comment by aki-sud** [comment]
i would like to contribute to this issue if you allow me to @EdwardDunn

**Comment by EdwardDunn** [comment]
@aki-sud Great idea, create a new PR when your ready. Let me know if you need any help.

**Comment by aki-sud** [comment]
Created a PR.

**Comment by EdwardDunn** [comment]
Completed by @aki-sud
