### ISSUE TITLE
Mute music and more instructions at game start

### ISSUE THREAD

**Issue by kedpak** [EdwardDunn/Platform-Game#75]
Hello, I like to play my own music when playing games. So I implemented a toggle music key. Also I was also working on a way to pause the game, however a pause feature is already implemented but I did not know due to no instructions. I added some more instructions at game start to pause and toggle music.

**Comment by EdwardDunn** [comment]
@kedpak Good idea to add a mute music feature. The game instructions were updated this morning to show the new pause feature. If you need any help just let me know. Thanks for your interest.

**Comment by kedpak** [comment]
I get this error when pushing. remote: Permission to EdwardDunn/Platform-Game.git denied to kedpak. Can you give me access?

**Comment by EdwardDunn** [comment]
Completed by @kedpak
