### ISSUE TITLE
Create objects instead of arrays (e.g. the keyCodes UP, DOWN...)

### ISSUE THREAD

**Issue by razmit** [EdwardDunn/Platform-Game#78]
Hi guys, just a little suggestion.
For the sake of making the code more easily to read and manipulate, you could create an **Object** to store keys which represent values, in this case, to store the **keyCode** for the Arrow keys (UP, DOWN, RIGHT, LEFT)
Something like this: 

`const keys = {

    UP: 38,

    DOWN: 40,

    LEFT: 37,

    RIGHT: 39

} `

So, in order to invoke any value within the **keys** Object you would use 

` switch ( //validate stuff here) {

            case keys.UP:

                    // Crazy-amazing-smoked-mind-bending stuff here

            break;

            case keys.DOWN:

                   // U wot m8

            break;`

And so on

All of this is just for sake of making it easier and more readable code, since I've worked with Canvas before and also did a mini-minuscule-game.

Good luck guys, amazing work so far!

**Comment by EdwardDunn** [comment]
@CommieTaco Thanks for your input, much appreciated!

**Comment by kanlanc** [comment]
Is this issue still available?

**Comment by EdwardDunn** [comment]
@highskillzz Hey, yeah this issue is available. 

Just leave a comment in you need any help.

**Comment by aricalves** [comment]
@highskillzz Are you still on this issue? If you're stuck, I can help!

**Comment by EdwardDunn** [comment]
Complete by @Germlord
