### ISSUE TITLE
Add sound effects

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#8]
It would be good to have sound effects for the movement of the main character. 

**Sounds**
- Jump
- Game over
- Background music

Please only use copyright free music/sounds, and update the copyright file with the sources.

**Comment by iamstratos** [comment]
I have sounds, I will reduce the filesizes and upload them. I may find time to add them into the game too.

**Comment by maanvin** [comment]
I have worked on this. Added all the sounds mentioned above, to the game. Can I make a pull request?

**Comment by iamstratos** [comment]
@maanvin I've found some sounds but I've got no time to add them in the problem. It's fine by me, go ahead!

**Comment by maanvin** [comment]
@iamstratos Thank you!
