### ISSUE TITLE
Add Enemy Killed Sound Effect

### ISSUE THREAD

**Issue by EdwardDunn** [EdwardDunn/Platform-Game#82]
**Add Enemy Killed Sound Effect**

Currently when the player character jumps on an enemy character, the enemy dies. However, there is no sound effect for this.

Add a short sound clip for this. Make sure any sounds used are copyright free and add their source into the copyrights.txt file.

If you need and help or have a suggestion, just leave a comment.

**Comment by akshatm147** [comment]
@EdwardDunn  I would like to work on this issue. Can you help me giving suggestions as how can I add the sound effects as I don't know how to do so and would like to learn that.

**Comment by EdwardDunn** [comment]
@chotuaashiq thanks for your interest in the project. If you have a look at how the jump sounds are implemented it will be very similar for the enemy killed sound effect. Have a look at the game.js file and try to understand the different parts. 

This part of the code in the KeyDown function activates the jump audio;

if (keysPressed[UP]) {
		jump_audio=document.getElementById("jump")
		jump.autoplay=true;
		jump.load();
		moveUp();
	}


If you do a similar thing in the updateGameArea function in the enemy characters for loop. 

Give it a go and let me know how you get on.

**Comment by akshatm147** [comment]
@EdwardDunn I did the same thing but the sound is still not working.

**Comment by EdwardDunn** [comment]
@chotuaashiq if you submit a PR  with your progress so far I will take look.

**Comment by prakharcipher** [comment]
I'd like to pick this issue up and solve it.

**Comment by prakharcipher** [comment]
@EdwardDunn I'd like to pick this issue up and solve it.

**Comment by EdwardDunn** [comment]
@prakharcipher Great, go ahead. I don't think @chotuaashiq is still working on it.

**Comment by prakharcipher** [comment]
@EdwardDunn Hey man. I just picked and fixed it. Please do have a look. Thanks.

**Comment by Redarcher9** [comment]
Is this issue solved?

**Comment by EdwardDunn** [comment]
@Redarcher9 No, feel free to take it up.

**Comment by tata81** [comment]
Hi @EdwardDunn  Is this issue still open ? Would like to work on this issue ?Thanks
Update: Fixed this issue and tested in my local machine. If no one is working on this issue I am happy to submit pull request. Thanks

**Comment by EdwardDunn** [comment]
Completed by @tata81
