### ISSUE TITLE
Documentation needs better formatting

### ISSUE THREAD

**Issue by ghost** [EdwardDunn/Platform-Game#83]
The current docs (README and CONTRIBUTING) could use an overhaul to make them easier for newcomers to read. Also, Contribution_Guide.md [should be named CONTRIBUTING.md for consistency](https://opensource.guide/how-to-contribute/#anatomy-of-an-open-source-project).

**Comment by EdwardDunn** [comment]
@mdawsondev Anything that makes it easier for newcomers is welcome. Just let me know if you need clarification on anything etc.

**Comment by EdwardDunn** [comment]
Completed by @mdawsondev
