### ISSUE TITLE
Option to disable sound effects.

### ISSUE THREAD

**Issue by Scruffy21** [EdwardDunn/Platform-Game#87]
Hello
This is a nice project, I'd like to try to help with it.

I noticed there's a key to disable music but no key to disable sound. And the jumping sounds might be a bit annoying to some people. It'd be nice to either add a key to disable the sound effects (for example 'e') or attach this to the 'm' key so that disabling music also disables sound effects.

If you think it's a good idea then I can try to implement this.

**Comment by EdwardDunn** [comment]
@scruffy21 Thanks for your interest. Good idea, I think adding it to the existing 'm' button would be best.

Just leave a comment if you need any help.

**Comment by Scruffy21** [comment]
Actually I'm a bit confused about the lines 57-59. The code assigns _jump_audio_ to the audio element, but then _jump_audio_ is never used again. Instead _jump_  is used. But it works, so I have no idea what's happening there. Would you mind explaining?

**Comment by EdwardDunn** [comment]
@Scruffy21 Good spot, that seems to have been left behind after the code was refactored to add the mute music function. You can remove 'jump_audio=document.getElementById("jump")' completely, open up a new PR for it.

**Comment by Scruffy21** [comment]
My confusion was because there was no element being assigned to the variable jump, so didn't know how it still worked. I've tried it out and it seems that you can just reference an element by its id, without needing to do document.getElementById. Didn't know that. :)

**Comment by EdwardDunn** [comment]
Completed by @Scruffy21
