### ISSUE TITLE
Fix startlevel functions

### ISSUE THREAD

**Issue by mordore4** [EdwardDunn/Platform-Game#99]
Right now there are multiple startlevel functions while there is lots of code that just repeats itself in each function. Just merging these into one function will make adding new levels way easier .

**Comment by EdwardDunn** [comment]
@mordore4 I agree, there is way to much code duplication!

**Comment by mordore4** [comment]
Fixed this one, there's a small merge conflict awaiting to be resolved now tho :p

**Comment by mordore4** [comment]
Hmm, must have been a mistake while fixing the merge conflict. I'll have a look at it later today, shouldn't take too long to figure it out since it worked just fine before resolving the conflict.

**Comment by mordore4** [comment]
Found the issue, I tested with immortality. If you can reverse reversing the merge I can fix it in 1 minute. Else it would take me close to an hour to figure out how exactly to fix it because your reverse is ahead of my branch.

**Comment by EdwardDunn** [comment]
@mordore4 I have undone the revert, can you make your change as soon as possible, thanks!

**Comment by EdwardDunn** [comment]
Sorry @mordore4 I couldn't wait any longer on you fixing the issue due to it effecting other users. I have removed the code for setting multiple lives myself.

Thanks for your contributions though, they have drastically improved the code!
